### ISSUE TITLE
[PluginRepo] Shows installed even tho not installed. Typo in the in-app notification "New plugin avaible"

### ISSUE THREAD

**Issue by WitherredAway** [mantikafasi/AliucordPlugins#14]
It shows i have these plugins installed and shows an "uninstall" even tho i don't and have never installed them before.
![Screenshot_2022-02-18-02-04-25-930_com aliucord](https://user-images.githubusercontent.com/81734495/154566490-cca8685c-e892-4447-969a-f4101818b596.jpg)
Does this for a lot if plugins.

Also, there is a typo in the notification when a new plugin comes out. "available" is written as "avaible" or something.

**Comment by mantikafasi** [comment]
Hm,I know this bug existed but it was happening too rarely. I'll take a look to that again

**Comment by mantikafasi** [comment]
it should be fixed rn
