### ISSUE TITLE
[EditMessagesLocally] Icon colour is incorrect

### ISSUE THREAD

**Issue by MMK21Hub** [mantikafasi/AliucordPlugins#22]
In the message context/popup menu, the icon for the "Edit Message Locally" button is always white, so it doesn't match the other icons in the menu.

This is easiest to see when using a theme that changes those icon colours (the Edit Message Locally icon doesn't seem to respect the themed colour), but the issue is also present and visible when using the default theme.

### Screenshots

![Default theme](https://user-images.githubusercontent.com/50421330/165093749-b62d9248-fcbf-436e-9ee1-8780519c0ff9.png)
![Custom theme](https://user-images.githubusercontent.com/50421330/165093895-bb5e1985-c9a8-4513-9310-92719b81fcab.png)

**Comment by mantikafasi** [comment]
fixed on latest version
