### ISSUE TITLE
[VoiceMessages]

### ISSUE THREAD

**Issue by DeRusGAMING** [mantikafasi/AliucordPlugins#32]
Inconveniences:
1)There is no way to delete the message as it's being recorded.
Suggested fix: add a slider, similar to the original discord app, where if slid to, it will delete the concept. If unable, make a confirmation screen after a finger is released

2)If you release your finger outside the text box, the recording starts to go forever, unable to be sent.
Suggested fix: extend the area where the finger is detected, if unable, make the recording end unless it can detect the finger inside the area

3) The plugin does not remember where was the memo recorded so if you start recording in one channel and move to another after you released a finger, but it didn't send yet, it will send itself to the actual channel you are in.
Suggested fix: make the plugin remember the selected user at the moment the recording starts and after it's done processing pull this information from a variable so it can be used for a call to Discord API, if unable, make a pop-up box with a loading bar and a cancel button

4) The sound wave displayed while the recording is off centre
Suggested fix: Centre it, if unable, don't put it in, and make a different indicator showing the recording is on. I would also make it blue to better fit the Discord theme

Please note I don't know much about the API Aliucord uses, so take these suggestions as an inspiration.

**Comment by mantikafasi** [comment]
1,2,3 are solved idk what you mean in 4th one it looks centered to me

**Comment by mantikafasi** [comment]
I am not sure I fixed it but pushed a update

**Comment by DeRusGAMING** [comment]
Yeah, it looks fine now! 
![image](https://user-images.githubusercontent.com/88430167/236806408-2c4a39e5-34ed-4c52-8c67-4838303a1b57.png)
