### ISSUE TITLE
[Voice Messages] Pitch of the recording is wrong 

### ISSUE THREAD

**Issue by bonkmaykrQ** [mantikafasi/AliucordPlugins#36]
Recordings I send with the Voice Messages plugin are higher pitched than they should be.

**Comment by mantikafasi** [comment]
try going to settings and checking "increase sample size"

**Comment by bonkmaykrQ** [comment]
> try going to settings and checking "increase sample size"

Just noticed that. Fixed the issue.
Sorry for not checking beforehand
