### ISSUE TITLE
[PluginRepo] servers down?

### ISSUE THREAD

**Issue by Njezi** [mantikafasi/AliucordPlugins#37]
Pluginrepo doesn't show anything since yesterday.
![Screenshot_2023-06-28-00-00-20-372_com.aliucord.jpg](https://github.com/mantikafasi/AliucordPlugins/assets/93012064/678bdc3e-7888-462f-a9b2-c0dd2a707c9b)

**Comment by mantikafasi** [comment]
fixed

**Comment by mantikafasi** [comment]
fixed
