### ISSUE TITLE
[EditServersLocally] Feature Requests

### ISSUE THREAD

**Issue by Reinified** [mantikafasi/AliucordPlugins#4]
Soulz#0387.

-edit voice channel names
-edit server banners
-move the edit server options to this menu
![Screenshot_20211016-142743](https://user-images.githubusercontent.com/54984650/137598352-3d5c53a2-d07a-4f2b-aee6-bdfb65f894de.png)

**Comment by mantikafasi** [comment]
i did the first and third one but rn Im too lazy to add banner support

**Comment by Reinified** [comment]
> i did the first and third one but rn Im too lazy to add banner support

well add it anyway before other people request it
