### ISSUE TITLE
[EncryptDMs] Please Continue it's development🙏

### ISSUE THREAD

**Issue by zerobun** [mantikafasi/AliucordPlugins#43]
Please continue the evenoemt of this plugin as it will be a major help with privecy in discord. Less user data will be taken from users.
I honestly think this plugin overtime can be a bit thing in the client side of discord as a whole ig we r we relate it to complete user messaging data privecy.
It's orerty obv how discord is most likely selling and sharing our info with other conaonies as they are mostly owned by a Chinese company so user data transparency to the Chinese gov is compulsery.

**Comment by mantikafasi** [comment]
it was kind of complicated and I no longer have motivation to work on it, so sadly its not happening

**Comment by zerobun** [comment]
> it was kind of complicated and I no longer have motivation to work on it, so sadly its not happening

Thanks for atleast trying, appreciate it. Have agrst day/night.
