### ISSUE TITLE
How to install this

### ISSUE THREAD

**Issue by NetherDragonTw** [mantikafasi/AliucordPlugins#44]
there is no website for this like other or something else so idk how to install it

**Comment by mantikafasi** [comment]
install what

**Comment by MuubNito** [comment]
> there is no website for this like other or something else so idk how to install it

All of those plugins are made for aliucord, so you will need that and to go to their discord server.
After that, search a message in #plugins-list with the plugin name, hold the message and you will see something about plugins (Probably PluginDownloader), you click in that, and then tap on "Install (PluginName)".
